name: Build and deploy to production

on:
  repository_dispatch:
    types: [save_post]
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Cache
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/.next/cache
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    
    - name: Build
      env:
        WP_API_URL: ${{ secrets.WP_API_URL }}
        GOOGLE_CALENDAR_ID: ${{ secrets.GOOGLE_CALENDAR_ID }}
        GOOGLE_CALENDAR_API_KEY: ${{ secrets.GOOGLE_CALENDAR_API_KEY }}
        GA_TRACKING_ID: ${{ secrets.GA_TRACKING_ID }}
      run: |
        npm ci
        npm run export-prod

    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        LOCAL_DIR: ./out/
        REMOTE_DIR: ${{ secrets.FTP_DIRECTORY }}
        METHOD: sftp
        PORT: 22
        ARGS: --delete --verbose --parallel=4
