name: Build and deploy to staging

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Cache
      uses: actions/cache@v1
      with:
        path: ${{ github.workspace }}/.next/cache
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12'
    
    - name: Build
      env:
        WP_API_URL: ${{ secrets.WP_API_URL }}
        GOOGLE_CALENDAR_ID: ${{ secrets.GOOGLE_CALENDAR_ID }}
        GOOGLE_CALENDAR_API_KEY: ${{ secrets.GOOGLE_CALENDAR_API_KEY }}
        GA_TRACKING_ID: ${{ secrets.GA_TRACKING_ID }}
      run: |
        npm ci
        npm run export-staging
    
    - name: Deploy
      env:
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
        FTP_DIRECTORY: ${{ secrets.STAGING_FTP_DIRECTORY }}
      run: |
        sudo apt install -yqq lftp
        lftp $FTP_SERVER -e "set sftp:auto-confirm yes ; mirror -R ./out/ $FTP_DIRECTORY"
