name: Build and deploy to GitHub Pages

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Build site
      uses: actions/setup-node@v1
      with:
        node-version: '12'
    - run: npm install
    - run: npm run export
      env:
        WP_API_URL: ${{ secrets.WP_API_URL }}
    - run: touch out/.nojekyll

    - name: GitHub Pages Deploy
      uses: maxheld83/ghpages@v0.2.1
      env:
        BUILD_DIR: out
        GH_PAT: ${{ secrets.GH_PAT }}